Repository opensearch-project/ansible-playbook, pull requests merged in 2022-10, with the labels that each got.

#81 [1.x] Fix nonexistent "os_sec_plugin_conf_path" directory error.
  roles/linux/opensearch/tasks/security.yml
Labels: backport 1.x

#97 Fix nonexistent os_sec_plugin_conf_path directory error
  roles/linux/opensearch/defaults/main.yml
  roles/linux/opensearch/tasks/security.yml
Labels: bug

#99 [Backport 1.x] Fix securityadmin.sh when copy_custom_security_configs is False
  roles/linux/opensearch/tasks/security.yml
Labels: bug, backport 1.x

#98 [Backport 1.x] become: false on "Check that the files/internal_users.yml exists"
  roles/linux/opensearch/tasks/security.yml
Labels: bug, backport 1.x
